version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgresql-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: genea
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/home/rajanladani/data/volume/postgresql

  zookeeper:
    image: zookeeper:3.7.0
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper


  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      AUTH_SERVICE_URL: http://auth-service:8081
      TASK_SERVICE_URL: http://task-service:8082
    depends_on:
      - auth-service
      - task-service

  auth-service:
    build: ./auth-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/genea    
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  task-service:
    build: ./task-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/genea
      BOOTSTRAP_SERVER: kafka:29092
    depends_on:
      - postgres
      - kafka
  
  notification-service:
    build: ./notification-service
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVER: kafka:29092      
    depends_on:
      - kafka

volumes:
  pg_data:
